### ISSUE TITLE
[ 贊助商機器 ] 跟註冊機器讀出的數值不同

### ISSUE THREAD

**Issue by timtan** [wagamama/pyconapac-rpi#2]
![2015-05-23 15 02 47](https://cloud.githubusercontent.com/assets/179785/7782908/4320d650-0160-11e5-88b6-a72023fd6b63.jpg)

上面是用註冊機讀出的

![2015-05-23 15 20 49](https://cloud.githubusercontent.com/assets/179785/7782910/50c386d6-0160-11e5-8b23-cbbdce3b07f6.jpg)
上面是用贊助機的資料

到時候資料不同，會發生困擾

**Comment by timtan** [comment]
使用正確的卡片。 並且要做 10進位轉  16 進位

**Comment by timtan** [comment]
這裏需要有人把  10 進位轉成 16 進位

**Comment by sosorry** [comment]
正確的卡片格式應該像 "1b  b6  d5  09"

**Comment by timtan** [comment]
好的。 看來沒有問題  等我 implement 好才關 feature

**Comment by lucemia** [comment]
https://github.com/wagamama/pyconapac-rpi/tree/add-sponsorship-program
