### ISSUE TITLE
[ 贊助商機器 ] 如何知道機器 ID

### ISSUE THREAD

**Issue by timtan** [wagamama/pyconapac-rpi#3]
贊助的需求。

需要知道機器的 ID  / 或是 SD Card ID

**Comment by raspberrypi-tw** [comment]
機器id : cat /proc/cpuinfo | grep Serial | awk ' {print $3}'
sd卡id : ls -l /dev/disk/by-uuid/ | grep mmcblk0p2 | awk '{print $9}'

reference:
- http://raspberrypi.stackexchange.com/questions/2086/how-do-i-get-the-serial-number
- http://www.cnblogs.com/dkblog/archive/2011/08/30/2159630.html
