### ISSUE TITLE
[ 贊助商機器 ]  感應成功以後要 Beep

### ISSUE THREAD

**Issue by timtan** [wagamama/pyconapac-rpi#6]
這裏要童叟無欺。

感應成功以後要 Beep  一下。

**Comment by lucemia** [comment]
現在有辦法了嗎?

**Comment by sosorry** [comment]
有阿 我們的機器都已經有這個功能了

你們直接使用這個檔案
https://github.com/wagamama/pyconapac-rpi/blob/master/buzzer.py

在讀到的後面加上這行
os.system("sudo python /home/pi/pyconapac-rpi/buzzer.py &")

就這樣
- sosorry

**Comment by lucemia** [comment]
thanks :)

**Comment by lucemia** [comment]
@sosorry  我們比較習慣不要太多透過直接互叫的方式的話 這樣改行嗎？
https://github.com/wagamama/pyconapac-rpi/blob/sponsor-buzz/lib/buzzer.py

**Comment by lucemia** [comment]
@sosorry  不會叫..

**Comment by lucemia** [comment]
這台 pin 是 12
